services:

  minio:
    image: minio/minio
    container_name: minio
    networks:
      - warehouse-net
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  create-bucket:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - warehouse-net
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 admin password;
      mc mb -p local/warehouse || true;
      exit 0;
      "

  rest:
    image: tabulario/iceberg-rest:latest
    container_name: iceberg-rest
    depends_on:
      - create-bucket
    networks:
      - warehouse-net
    ports:
      - "8181:8181"
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      AWS_REGION: us-east-1
      CATALOG_WAREHOUSE: s3://warehouse/
      CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
      CATALOG_S3_ENDPOINT: http://minio:9000
      CATALOG_S3_PATH__STYLE__ACCESS: "true"


  trino:
    image: trinodb/trino:440
    container_name: trino
    depends_on:
      - rest
    networks:
      - warehouse-net
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/etc/trino

# networks:
#   lake_net:
#     driver: bridge

networks:
  warehouse-net:
    external: true

